'use client'
import './globals.css'
import { createContext, useReducer } from 'react'
import { reducer } from '@/contexto/generalReducer'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export const contexto = createContext()

const initalState = {
  contador:0
}
export default function RootLayout({ children }) {
  const [state, dispatch] = useReducer(reducer, initalState)
  return (
    <html lang="en">
      <contexto.Provider value={{state, dispatch}}>
      <body>{children}</body>
      </contexto.Provider>
      
    </html>
  )
}
